// #define GREETING_TPC "/HOME_AUTOMATION/GREETING"
// #define MOTION_SENSOR_STATE_TPC "MotionSensors/Hall"
// #define DEVICE_OPERATION_CONTROL_TPC "Devices/Operation/Control"
// #define DEVICE_OPERATION_MODE_TPC "Devices/Operation/Mode"
#define MOTION_SENSOR_ID "HALL_SENSOR_TABLE_1"
#define RELAY_HIGH 0

#define MAX_ON_OPERATION_MODE_DURATION_MS 60000

#define GREETING_TPC "/HOME_AUTOMATION/GREETING"

#define AUTHORIZATION_REQUESTS_TPC "/HOME_AUTOMATION/AUTHORIZATION_REQUESTS"
#define AUTHORIZATION_REQUESTS_STATUS_TPC "/HOME_AUTOMATION/AUTHORIZATION_REQUESTS_STATUS"

#define GET_DEVICE_SETTINGS_TPC "/HOME_AUTOMATION/GET_DEVICE_SETTINGS"
#define UPDATE_DEVICE_SETTINGS_TPC "/HOME_AUTOMATION/UPDATE_DEVICE_SETTINGS"
#define APPLY_DEVICE_SETTINGS_TPC "/HOME_AUTOMATION/APPLY_DEVICE_SETTINGS"

#define BASE_LOCATION_TPC "/HOME_AUTOMATION/HALL"

#define MOTION_TPC "/HOME_AUTOMATION/HALL/MOTION"
